### ISSUE TITLE
Funcionamento da Tela de Coordenadores E Professores

### ISSUE THREAD

**Issue by IgorRibeiroGuimaraes** [IgorRibeiroGuimaraes/faculdade_project#10]
- [x] Após a validação da tela login, deve ser direcionado para home page do Coordenador/Professor
- [x] Home page deve conter uma listagem do curso a qual ele foi cadastrado, e com os semestre 
- [x] Após clicar uma delas direcionará em uma tela que ele poderá digitar e avisar possíveis comunicados 
- [x] Mensagem anteriores devem ser apresentado, e depois apagar tudo depois quando acabar o semestre
- [x] Mensagem devem conter a data que foi mandada e o conteúdo dela 
- [x] Resolver alguns Bug relacionado ao envio de mensagem mostrado mais a baixo 

![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/98341243/2b829c38-e681-4672-aaa1-47d7157617f9)

![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/98341243/06b998a1-25ce-4fe0-8eb4-39c4f0d477bc)

**Comment by Lucas-Peixoto-Pereira** [comment]
Sobre a task validação da tela login
![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/7f9ce9e4-eb9f-4f54-b675-2be84ab853ce)

Login de coordenador está funcionando normalmente vale ressaltar que ainda não foi implementado uma função para distinguir login de professor e de coordenador.

**Comment by Lucas-Peixoto-Pereira** [comment]
Sobre a task de listagem de curso

**Implementação do codígo**
```
List<Map<String, dynamic>> courses = snapshot.data!;
            return ListView.builder(
              itemCount: courses.length,
              itemBuilder: (context, index) {
                var course = courses[index];
                return Card(
                  margin: EdgeInsets.all(8.0),
                  child: ListTile(
                    title: Text(course['name']),
                    subtitle: Text(
                        'Período: ${course['period']}, Semestre: ${course['semester']}'),
                    onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) =>
                              CourseChatPage(courseName: course['name']),
                        ),
                      );
```
Na home foi mapeado uma lista que ira puxar do banco todos os cursos que foram selecionados pelo usuário na pagina de cursos.

![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/b5ee51bf-5c92-4b6b-b3ca-2fa8ff7081ef)

**Comment by Lucas-Peixoto-Pereira** [comment]
Sobre a task de redirecionamento para o chat clicando no curso
Implementação do código:
```
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          'Chat ${widget.courseName}',
          style: TextStyle(color: Colors.white),
        ),
        backgroundColor: Colors.black87,
        iconTheme: IconThemeData(color: Colors.white),
      ),
      body: Column(
        children: [
          Expanded(
            child: StreamBuilder(
              stream: _firestoreService.getMessages(widget.courseName),
              builder: (context, AsyncSnapshot<QuerySnapshot> snapshot) {
                if (!snapshot.hasData) {
                  return Center(child: CircularProgressIndicator());
                }
                var messages = snapshot.data!.docs;
                return ListView.builder(
                  itemCount: messages.length,
                  itemBuilder: (context, index) {
                    var message = messages[index];
                    return ListTile(
                      title: Text(message['message']),
                      subtitle: Text(
                          _formatTimestamp(message['timestamp'] as Timestamp)),
                    );
                  },
                );
              },
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _messageController,
                    decoration: InputDecoration(
                      hintText: 'Digite sua mensagem...',
                      filled: true,
                      fillColor: Colors.white,
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(10.0),
                      ),
                    ),
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.send),
                  onPressed: _sendMessage,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

Foi reutilizado o código que ja existia de chat adicionando apenas timestamp e outros elementos para aparecer na mensagem do chat

![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/7b43ec68-1fd9-44d1-8cd5-14f3e8a09be5)

**Comment by Lucas-Peixoto-Pereira** [comment]
Sobre a task do timestamp na mensagem

Como dito anteriormente já foi implementado o timestamp em todas as mensagens enviadas pelo coordenador.

![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/9e4d6361-dfa6-42d4-ab59-75017c4f75f5)

**Comment by IgorRibeiroGuimaraes** [comment]
Resolver o Problema das mensagem persistindo em outros chat @Lucas-Peixoto-Pereira

**Comment by IgorRibeiroGuimaraes** [comment]
Resolver este Problema vinculado a  tela de chat @Lucas-Peixoto-Pereira 




https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/98341243/5f8ff5ce-59c5-424f-9d1d-22d2c1de7526

**Comment by Lucas-Peixoto-Pereira** [comment]
Corrigido o erro de time stamp, agora ele não aparece mais.
