### ISSUE TITLE
Cadastro de Curso

### ISSUE THREAD

**Issue by IgorRibeiroGuimaraes** [IgorRibeiroGuimaraes/faculdade_project#11]
- [x] Cadastrar um nome de um Curso 
- [x] Cadastrar o Período existente do Curso sendo (Matutino, Vespertino, Noturno) 
- [x] Cadastrar a quantidade de semestre no máximo por enquanto 10 semestre 

**Lembrando que Pode somente 1 curso, mas o período pode mudar exemplo, Engenharia de Software, Matutino, Vespertino, Noturno Se o curso for só um período deixa como booleano** 

![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/98341243/71ea3439-679c-49bd-9d29-f14e13612722)

**Comment by IgorRibeiroGuimaraes** [comment]
o @Lucas-Peixoto-Pereira , irá fazer a parte de cadastro de semestre para o coordenador escolher a quantidade de semestre disponível do semestre

**Comment by Lucas-Peixoto-Pereira** [comment]
Foi adicionado uma lista com a quantidade de semestres para o usuário poder selecionar:


![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/8cbf3456-c3d5-4701-8f25-ddfea66e6ea4)
