### ISSUE TITLE
Cadastro de Professor/Coordenadores

### ISSUE THREAD

**Issue by IgorRibeiroGuimaraes** [IgorRibeiroGuimaraes/faculdade_project#12]
- [x] Validação de e-mail 'prof_nome@unicv.edu.br' 
- [x] Validação de Senha 
- [x] Telefone 
- [x] Curso a quais ele pertence
- [x] Modificar a Label para validar se é Coordenador ou Não e mandar essa informação para o Firestore 
![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/98341243/54dad399-0496-464d-87a8-c091403c0b47)

**Comment by Lucas-Peixoto-Pereira** [comment]
**Código implementado para validação de e-mail**
```
_buildTextField(
                    controller: _emailController,
                    labelText: 'Email',
                    icon: Icons.email,
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Por favor, insira seu e-mail';
                      } else if (!RegExp(r'^prof.*@unicv\.edu\.br$')
                          .hasMatch(value)) {
                        return 'Por favor, insira um e-mail válido!';
                      }
                      return null;
                    },
                  ),
```

Print dos testes
Teste 1: Tentativa de cadastro sem inserção de e-mail.
![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/4fc1c68b-d93a-4bec-b347-8728e71d942a)

Teste 2: Tentativa de cadastro com e-mail sem as condições atendidas.
![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/b0d902dd-9d47-4729-99bb-2f6079ea7155)

Foi implementado a validação de e-mail, utilizando do validator e o !RegExp para confirmar um padrão de e-mail.

**Comment by Lucas-Peixoto-Pereira** [comment]
Código implementado para validação de senha
```
_buildTextField(
                    controller: _passwordController,
                    labelText: 'Senha',
                    isPassword: true,
                    icon: Icons.lock,
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Por favor, insira sua senha';
                      } else if (value.length < 6) {
                        return 'A senha deve ter pelo menos 6 caracteres';
                      }
                      return null;
                    },
                  ),
```
Print dos testes
Teste 1: Tentativa de cadastro com 4 dígitos na senha.
![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/d447f8d5-2687-407a-977a-88f5844f91ce)

Teste 2: Tentativa de cadastro sem preenchimento de senha:
![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/c81a1ca3-fed7-4784-8aac-c920b22032a5)

Foi implementado a validação de senha que verifica se a senha está vazia ou se ela tem menos que 6 caracteres.
Foi adicionado uma confirmação de senha para impedir que ocorra futuros erros com as senhas do usuário.
![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/7c3f7549-f433-4a5f-a9d3-2d84945f984b)

**Comment by Lucas-Peixoto-Pereira** [comment]
Código implementado para validação de telefone
```
_buildTextField(
                    controller: _phoneNumberController,
                    labelText: 'Telefone',
                    icon: Icons.phone,
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Por favor, insira seu telefone';
                      } else if (!RegExp(r'^\d+$').hasMatch(value)) {
                        return 'Por favor, insira um telefone válido';
                      }
                      return null;
                    },
                  ),
```
Print dos testes
Teste 1: Tentativa de cadastro sem preenche o campo.
![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/db4e17cf-c025-4c73-bc14-7443962c3020)

Teste 2: Tentativa de cadastro utilizando letras.
![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/7b781eb2-abf7-4d82-8d03-f1e18716f730)

Foi implementado a validação telefone não permitindo campo vazio ou utilizando string no campo.

**Comment by Lucas-Peixoto-Pereira** [comment]
**Sobre o curso**
Foi deixado apenas um campo para o usuário digitar o curso em que ele pertence futuramente poderemos encontrar uma forma de implementar uma lista de cursos ou uma outra maneira do usuário informa o curso a que pertence.
![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/2f699f41-ead3-44eb-8196-437c600635d1)

**Comment by Lucas-Peixoto-Pereira** [comment]
Sobre a task da barra de semestre
Foi retirada com sucesso.
![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/ba837cdb-7810-4365-af0d-f6b804365ccb)

**Comment by Lucas-Peixoto-Pereira** [comment]
Foi adicionado um campo role agora cada usuário vai ter registro se é coordenador ou professor.


![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/b3a41259-1a7d-4e58-9f7b-fb316d3aae85)

**Comment by Lucas-Peixoto-Pereira** [comment]
Bug corrigido era um erro de time stamp
