### ISSUE TITLE
[Front-End] Problema de Image não estar parecendo no Android

### ISSUE THREAD

**Issue by IgorRibeiroGuimaraes** [IgorRibeiroGuimaraes/faculdade_project#21]
Problema da Logo Principal não estar aparecendo no Android na tela de Login 

Segue a imagem do Problema 

![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/98341243/9e15c52f-06bc-471b-b933-d7d0c59931cd)

**Comment by Lucas-Peixoto-Pereira** [comment]
![image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/6054c11f-3ae6-4962-bedc-fb7221443210)

Bug corrigido! Quando for colocar uma imagem proveniente do assets, o caminho inicia sem o barra. ex ('"assets/images/news.png")

**Comment by Lucas-Peixoto-Pereira** [comment]
Acredito ter corrigido todos os bugs com as imagens!
