### ISSUE TITLE
Modificação da Tela Home do Professor

### ISSUE THREAD

**Issue by IgorRibeiroGuimaraes** [IgorRibeiroGuimaraes/faculdade_project#33]
Se a Pessoa cadastrada for professor não irá aparecer o campo de cadastro de curso pois somente o Coordenador poderá fazer esse cadastro 

![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/98341243/615c72d6-1666-4c0c-a66b-98c4f3082ee2)

**Comment by Lucas-Peixoto-Pereira** [comment]
Agora como o sistema puxa a role foi criado uma condicional para o botão aparecer apenas para o coordenador.


![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/16801786-7b92-4e9a-9eda-dfcff641e7d0)
