### ISSUE TITLE
[Funcionalidade] Comunicação de Aluno e Chat

### ISSUE THREAD

**Issue by IgorRibeiroGuimaraes** [IgorRibeiroGuimaraes/faculdade_project#41]
Necessita-se de quando o Aluno cadastrar cair diretamente na tela de chat do próprio curso

**Comment by Lucas-Peixoto-Pereira** [comment]
Implementado agora quando o aluno fizer o login ele irá cair diretamente no mural de chat do seu respectivo curso.
