### ISSUE TITLE
[Bug] Problema na Home do Estudante

### ISSUE THREAD

**Issue by IgorRibeiroGuimaraes** [IgorRibeiroGuimaraes/faculdade_project#43]
Estou enfrentando um problema, a qual quando o estudante cadastra-se ele não consegue escolher direito o chat, todavia se ele sai e entra novamente ele consegue sem contar com o problema na autenticação em conjunto

**Comment by Lucas-Peixoto-Pereira** [comment]
Agora ao cadastrar-se como aluno teremos uma lista onde o mesmo poderá selecionar seu curso e semestre:


![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/47579b43-1e83-408a-a72f-d4199f65e8d9)



![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/11b43dc6-d006-4738-b92e-b704afa51a7e)

E ao logar ele ira aparecer no chat do seu respectivo curso
