### ISSUE TITLE
Testes login aluno

### ISSUE THREAD

**Issue by Lucas-Peixoto-Pereira** [IgorRibeiroGuimaraes/faculdade_project#44]
- [x] Verificar se o aluno consegue efetuar o login corretamente.

- [x] Verificar se ao efetuar o login o aluno e redirecionado a tela de chat

- [x] Verificar se o aluno consegue usar as reações do chat

- [x] Verificar se o aluno consegue realizar logout

**Comment by MathSantana1** [comment]
Foi cadastrado um email sem ser o @Aluno.unicv.edu.br e mesmo assim foi realizado login, o mesmo email subiu para o firebase 

![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/108034666/946bb5ff-cf11-4c6a-be3e-e4201d366d44)

**Comment by Lucas-Peixoto-Pereira** [comment]
Corrigido! Seguindo o padrão de " texto . número - número @aluno.unicv.edu.br "

![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/3574326e-2a19-4900-80b0-76177892a490)

**Comment by MathSantana1** [comment]
Quando é feito cadastro feito corretamente, é possível realizar o login corretamente
