### ISSUE TITLE
Testes login professor

### ISSUE THREAD

**Issue by Lucas-Peixoto-Pereira** [IgorRibeiroGuimaraes/faculdade_project#46]
- [x]  Verificar se o professor consegue efetuar o login corretamente.

- [x]  Verificar se ao efetuar o login o professor e redirecionado a sua home

- [x]  Verificar se o professor consegue usar as reações do chat

- [x]  Verificar se o professor consegue realizar logout

- [x] Verificar se o professor consegue enviar uma mensagem para seu curso

- [x] Verificar se o professor consegue deletar/editar sua propia mensagem enviada

- [x] Verificar se o professor consegue selecionar seu curso para envio de mensagem

**Comment by MathSantana1** [comment]
foi cadastrado o email prof_andradesantana3@unicv.edu.br com a senha 123456, porem não esta acessando como professor

![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/108034666/222e150e-7dbb-4cec-b055-bfe753642614)

**Comment by Lucas-Peixoto-Pereira** [comment]
Corrigido! Professor consegue fazer login. Existia uma condição que eu tinha esquecido de apagar e ela estava causando conflito. 



![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/4cfc400a-ee74-48ae-8681-c89e19ad61c5)

**Comment by MathSantana1** [comment]
![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/108034666/70da4b3a-76ed-42b2-b129-8f154dfa04ad)


![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/108034666/154d76be-e3c8-43fb-bb13-b13c36699dfa)


![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/108034666/6dee5d3c-9cc7-4856-b782-87840b8b235a)


foi cadastro o email prof_piao@unicv.edu.br, cadastro foi realizado com sucesso, porem quando irei realizar o login ele da da erro na validação, verificar!

**Comment by luizhenr01** [comment]
**Erros printados acima pelo Matheus , esta funcionando corretamente , era problema de sincronização nos códigos causados pelo Git !!!**
