### ISSUE TITLE
Teste cadastro de aluno

### ISSUE THREAD

**Issue by Lucas-Peixoto-Pereira** [IgorRibeiroGuimaraes/faculdade_project#47]
- [x] Verificar validação de cadastro do aluno
- [x] Verificar campos de cadastro de aluno e suas requisições

**Comment by MathSantana1** [comment]
testes realizados, todos as validações corretas, apenas no email que esta aceitando qualquer tipo de email invez do apenas @aluno

**Comment by Lucas-Peixoto-Pereira** [comment]
Corrigido! 

![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/148655809/32d8fc4f-25d1-4461-9265-173417948787)

**Comment by MathSantana1** [comment]
![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/108034666/c1804f0e-577d-4637-93b8-8f6463780660)

realizado o teste novamente, desde vez ele aceito esse tipo de email nesse formato porem, assim que realizo o cadastro e tento fazer login, ele da credencial errada, sendo que não era para aceitar o gmail como valido

**Comment by MathSantana1** [comment]
realizado teste novamente, e fazendo cadastro corretamente!
