### ISSUE TITLE
Testes cadastro professor

### ISSUE THREAD

**Issue by Lucas-Peixoto-Pereira** [IgorRibeiroGuimaraes/faculdade_project#48]
- [x] Verificar validação de cadastro do professor
- [x] Verificar campos de cadastro do professor e suas requisições

**Comment by MathSantana1** [comment]
acredito ser util colocar para verifica a sua senha antes de cadastra, para não ocorrer o risco de colocar errado

![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/108034666/9d2baeda-0635-46bc-9e76-4bcafc69aab2)
