### ISSUE TITLE
Testes login coordenador

### ISSUE THREAD

**Issue by Lucas-Peixoto-Pereira** [IgorRibeiroGuimaraes/faculdade_project#49]
- [x]  Verificar se o coordenador consegue efetuar o login corretamente.
- [x]  Verificar se ao efetuar o login o coordenador e redirecionado a sua home
- [x]  Verificar se o coordenador consegue usar as reações do chat
- [x]  Verificar se o coordenador consegue realizar logout
- [x]  Verificar se o coordenador consegue enviar uma mensagem para um curso cadastrado
- [x] Verificar se o coordenador consegue adicionar um novo curso
- [x]  Verificar se o coordenador consegue deletar/editar sua propia mensagem enviada
- [x]  Verificar se o coordenador consegue selecionar mais de um semestre para para envio de mensagem

**Comment by luizhenr01** [comment]
![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/134110438/94b5e323-3e1e-4fd1-bfed-7ab188e43e0d)

Cadastrando Curso Existente novamente  



![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/134110438/e01cfe7d-248c-4503-8b12-af45587e25a3)

Consequentemente esta duplicando os semestre caso seja o mesmo curso cadastrado mais de uma vez 



![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/134110438/b85cd490-859c-4c57-ba69-515978e5df34)


![Image](https://github.com/IgorRibeiroGuimaraes/faculdade_project/assets/134110438/f5d2a5de-ab2d-4d8f-a1b6-e8eae38aa818)

Não Esta Aparecendo o Período do curso Cadastrado

**Comment by luizhenr01** [comment]
Testes de login Concluídos , apenas erros em algumas funcionalidades
